# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :betaTest do
    gradle(task: "clean -Dskip.tests -PversionName=#{getVersionNumber} -PversionCode=#{getVersionCode} assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

    def getVersionNumber
        if isPullRequest?
            return "PR-#{getPRNumber}"
        elsif isOnGitHubActions?
            return "#{ENV["PRE_RELEASE_NO"]}"
         else nil
        end
    end

    def getVersionCode
        if isPullRequest?
            return "5000"
        elsif isOnGitHubActions?
            return "#{ENV["BUILD_NUMBER"]}"
        else nil
        end
    end

    def isOnGitHubActions?
        return isOnCi? && ENV["JOB_NAME"] == "Github-Actions"
    end

    def isRelease?
        return isOnCi? && ENV["JOB_NAME"] == "Release-ATK"
    end

    def isOnCi?
        ciJobType = ENV["JOB_NAME"]
        return !ciJobType.to_s.empty?
    end
    def isPullRequest?
        if isOnGitHubActions?
            return !getPRNumber.to_s.empty?
        else
            return getBranchNameWithoutOrigin.start_with?('PR-')
        end
    end

    def getPRNumber
        if isOnGitHubActions?
            return ENV["PR_NUMBER"]
        else
            return getBranchNameWithoutOrigin.gsub("PR-", "")
        end
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
