name: Android Release

on:
  push

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Run Unit Tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11.0
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Assemble debug APP APK
        run: bash ./gradlew assembleDebug --stacktrace
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Android UI Tests
        run: bash ./gradlew assembleDebugAndroidTest
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}

      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  DEV:
    name: Run ui tests with firebase test lab
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'


    steps:

      - name: create apk
        run: |
          $GITHUB_WORKSPACE/gradlew clean -Dskip.tests  assembleDebugAndroidTest assembleDebug --stacktrace
          find $GITHUB_WORKSPACE -name "*.apk"

      - uses: 'actions/checkout@v3'


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_JSON_KEYFILE }}'


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'


  

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/app-debug/app-debug.apk --test app/build/outputs/apk/app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=26,locale=pl,orientation=portrait

      - name: Run firebase tests
        run: |
          gcloud firebase test android run --type instrumentation "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" "app/src/androidTest" 
