name: Pull Request

on:
  push:


jobs:
  Verify-Pull-Request:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Show GitHub ref
        run: echo "$GITHUB_REF"

      - uses: actions/upload-artifact@v3
        with:
          name: "Test Reports"
          path: app/build/reports/tests/

