name: Pull Request

on:
  push:

env:
  INCREMENT: ((1400+${{github.run_number}}))
  MAXS: "-dev-"

jobs:
  Verify-Pull-Request:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: |
          echo "BUILd_no=$((${{github.run_number}} + 200))" >> $GITHUB_ENV
          
      - run: echo $BUILd_no
      - name: Read version.txt file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./app/version.txt
      - name: Make version no
        run: echo "GIT_RUN=${{ steps.package.outputs.content }}"-dev-"${{env.BUILd_no}}" >> $GITHUB_ENV

      - run: echo "$GIT_RUN :rocket:"
      - run: echo $GIT_RUN ":rocket:"

#      - name: merge
#        run: echo "Git_fix=`echo ${{GIT_RUN}}${{MAXS}}${{github.run_number}}`" >> $GITHUB_ENV
#
#      - run: echo $Git_fix
        
#      - name: "Get latest tag"
#        id: latest_tag
#        run: echo "name=$(git tag --sort=-creatordate | head -1)"
#      - name: "Get second latest tag"
#        id: second_latest_tag
#        run: echo "name=$(git tag --sort=-creatordate | head -2 | tail -1)"
#


          
#      - run: echo $GIT_MERGE

#       - name: release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#         with:
#           tag_name: ${{ github.run_number }}
#           release_name: ${{ github.run_number }}

#      - name: Release to github
#        run: sh $GITHUB_WORKSPACE/release-to-github.sh
#        env:
#          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
#          REPO: "GitActionsPractice"
#          PRERELEASE: true
#          VERSION: "1.3.1"
        
#      - name: 'Get Previous tag'
#        id: previoustags
#        uses: "WyriHaximus/github-action-get-previous-tag@v1"
#        with:
#          fallback: 1.0.0
#
#      - name: 'Get Previous tag manually'
#        id: previoustagManually
#        run: |
#          echo "GIT_TAG_NO=  ${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV
#          echo "Timestamp: ${{ steps.previoustag.outputs.timestamp }}"
#          test -n "${{ steps.previoustag.outputs.tag }}"
#          test -n "${{ steps.previoustag.outputs.timestamp }}"
#

#
#      - name: Get the version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
#
#      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
#
#      - name: Show GitHub ref
#        run: echo "$GITHUB_REF"
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: "Test Reports"
#          path: app/build/reports/tests/
#
