name: Pull Request

on:
  push:

env:
  INCREMENTSA: 1a
  MAXS: 3

jobs:
  Verify-Pull-Request:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: merge
        run: |
          echo "GIT_MERGE=`echo $INCREMENTSA $MAXS`" >> $GITHUB_ENV
          
      - run: echo $GIT_MERGE

#       - name: release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#         with:
#           tag_name: ${{ github.run_number }}
#           release_name: ${{ github.run_number }}

#      - name: Release to github
#        run: sh $GITHUB_WORKSPACE/release-to-github.sh
#        env:
#          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
#          REPO: "GitActionsPractice"
#          PRERELEASE: true
#          VERSION: "1.3.1"
        
#      - name: 'Get Previous tag'
#        id: previoustags
#        uses: "WyriHaximus/github-action-get-previous-tag@v1"
#        with:
#          fallback: 1.0.0
#
#      - name: 'Get Previous tag manually'
#        id: previoustagManually
#        run: |
#          echo "GIT_TAG_NO=  ${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV
#          echo "Timestamp: ${{ steps.previoustag.outputs.timestamp }}"
#          test -n "${{ steps.previoustag.outputs.tag }}"
#          test -n "${{ steps.previoustag.outputs.timestamp }}"
#
#      - name: Test
#        run: |
#          (( RESULT = $GIT_TAG_NO + $INCREMENT ))
#          echo $RESULT
#          echo $GIT_TAG_NO
#
#      - name: Get the version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
#
#      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
#
#      - name: Show GitHub ref
#        run: echo "$GITHUB_REF"
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: "Test Reports"
#          path: app/build/reports/tests/
#
