name: Pull Request

on:
  pull_request:


jobs:
  Verify-Pull-Request:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      - uses: actions/upload-artifact@v3
        with:
          name: "Test Reports"
          path: app/build/reports/tests/

